ARG PYTHON_VERSION=3.11

FROM ghcr.io/vincentsarago/uvicorn-gunicorn:${PYTHON_VERSION}

ENV CURL_CA_BUNDLE /etc/ssl/certs/ca-certificates.crt

RUN python -m pip install stac-fastapi.api==2.4.8 stac-fastapi.extensions==2.4.8 stac-fastapi.pgstac==2.4.8 stac-fastapi.types==2.4.8 pygeoif==0.7 starlette_cramjam

ENV MODULE_NAME stac_fastapi.pgstac.app
ENV VARIABLE_NAME app
